/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3Gradle;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void AppFunction1Test() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.function1(), 1);
    }

    @Test public void AppFunction2Test() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.function2(), 2);
    }

    @Test public void AppFunction3Test() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.function3(), 3);
    }

    @Test public void AppFunction4Test() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.function4(), 4);
    }

}
