/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3Gradle;

public class App {

    public int function1() {
        return 1;
    }

    public int function2() {
        return 2;
    }

    public int function3() {
        return 3;
    }

    public int function4() {
        return 4;
    }

    public static void main(String[] args) {
    }
}
